### ISSUE TITLE
Closing out an outage in Dev doesn't show "send email button"

### ISSUE THREAD

**Issue by adriennecoon** [ITS-UofIowa/its.uiowa.edu#23] opened 2016-12-02 14:17 UTC
I was testing the Closed/Update label emails and noticed that after closing an outage, the page directs to /alerts instead of providing the email button. This occurs after editing an outage from /alerts page (using gear). This is different from prod, where I believe the page stays on the outage page instead of the alerts landing page.

**Comment by adamdelaney** [comment] 2016-12-02 15:09
I tested this behavior in stage where the code base is the same as prod and it does the same thing. If you look at the URL when editing from the alerts page using the contextual link you see `https://its.stage.drupal.uiowa.edu/node/106531/edit?destination=alerts` where a query parameter is added to redirect back to the alerts page. This works as designed. I would suggest  going to an alert node if you are closing it out in order to send the email notification. I'm closing this issue for now.

**Closed by adamdelaney** 2016-12-02 15:09 UTC

**Comment by adriennecoon** [comment] 2016-12-02 15:31
I tested this in prod and it looks like it is working as designed. However, how come editing from the gear on /alerts has a different behavior than editing from the dashboard? I think this should be consistent. 

If we're giving help desk editors the gear to edit the alerts from the alerts landing page, I worry they will miss this behavior (send email) unintentionally.

**Comment by adamdelaney** [comment] 2016-12-02 15:34
The behavior is different because the idea of contextual editing is to edit in place, so when you make an edit you are re-directed so you can continue as if you never left the place you where at.
