### ISSUE TITLE
". is not published" on icon info center

### ISSUE THREAD

**Issue by joewhitsitt** [ITS-UofIowa/its.uiowa.edu#51] opened 2017-02-08 15:05 UTC
![icon](https://cloud.githubusercontent.com/assets/4663676/22742795/aa9f5e58-eddd-11e6-999e-8aca9d8d8074.jpeg)

**Comment by adamdelaney** [comment] 2017-02-08 15:11
This is because the showcase that is attached to the info center is unpublished and it's title is ".". 
![screen shot 2017-02-07 at 11 50 08 am](https://cloud.githubusercontent.com/assets/1016880/22743046/8561da16-edde-11e6-99b1-b53d78714dca.png)

**Comment by adamdelaney** [comment] 2017-02-08 15:13
Marking this as wontfix as this works by design.

**Closed by adamdelaney** 2017-02-08 15:13 UTC
Labels: bug, wontfix
