### ISSUE TITLE
Closed Degradation of Service alerts emails should be marked "[CLOSED]" in subject line

### ISSUE THREAD

**Issue by adriennecoon** [ITS-UofIowa/its.uiowa.edu#84] opened 2018-01-24 14:01 UTC
However, I've seen a couple that have been marked Closed so this may be a bug.

**Comment by adriennecoon** [comment] 2018-01-24 14:04
Here's an example of an email that doesn't say "[CLOSED]" in the subject line even thought the alert has been closed out.
<img width="892" alt="alert email without closed in subjectline" src="https://user-images.githubusercontent.com/24274784/35336140-104a6bd6-00dd-11e8-9f03-24e47e6aeb5e.PNG">

**Comment by adriennecoon** [comment] 2018-01-24 14:05
Here's an example where the email does say "[CLOSED]":
<img width="444" alt="alert email with closed in subjectline" src="https://user-images.githubusercontent.com/24274784/35336260-5fe14390-00dd-11e8-94e9-0f09e3fd47e3.PNG">

**Comment by joewhitsitt** [comment] 2018-01-24 15:58
@adriennecoon 

My suspicion is that this is a workflow issue/limitation of the current logic and not a bug. The email will get a [CLOSED] tag if the alert has been closed (the closed field is checked). While this does automatically happen if the alert is back-dated, the automation only runs every five minutes. So in some cases, this automation can run AFTER the editor back dates, provides update text, saves and then triggers an email. I tried to track this down in the edit history, but it appears Drupal doesn't show changes to this checkbox...

So far, I have not had an issue with the [CLOSED] tag as long as I click the closed box before saving/sending the email.

If this is the case, and it doesn't meet the requirements, then we should look into extending or rewriting the logic to automate the closing on save if back dated.

While looking into this, I noticed it would be nice to have some kind of indicator on the alert node if the alert is closed besides a end date. Let us know if you feel the same and we could look into adding something.

**Comment by adriennecoon** [comment] 2018-01-24 22:38
Ok, I've forwarded your message to the HD. Hopefully manually checking the Closed button will fix the issue. 

Jamie really likes your idea to add some kind of indicator on closed alerts. Can something like that be added this iteration? 

Also, can moderation be turned on for alerts so that we can see editing history?

**Comment by joewhitsitt** [comment] 2018-01-25 16:28
I've added the indicator. I'll push back on adding moderation (draft/needs review) to the alert content type. It seems like just about everyone has permissions to see the "Revisions" tab on the alert node where one can view text changes of the alert but not things like the closed boolean... 

Unfortunately, this has made us realize that folks can also revert an alert and we can't change that unless we remove the permission across the whole site. So we ask that people don't revert alerts because it affects dates, email log, closed status, past alerts, aka the whole alert system.

**Comment by adriennecoon** [comment] 2018-02-01 20:23
Hey Joe---Sorry to do this to you, can you remove the indicator? Jamie like it for outages, but not for planned maintenance. Instead of keeping it for certain types of alerts, let's just remove it entirely. 

As for the CLOSED issue, the fix we're going with is that HD editors will manually check the closed checkbox. Hopefully that fixes the issue. 

Once the indicator is removed, we can move this item to Done.

**Closed** 2018-02-28 21:03 UTC
Labels: approved
